remote_theme: pages-themes/minimal@v0.2.0
title: Runbooks.sh
logo: https://i.ibb.co/s6RD5zS/logo-runbooks-4.png
description: Empowering Cloud Automation, Together.
show_downloads: true
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
