{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awesome-runbooks
  namespace: {{ .Release.Namespace }}
  labels:
    app: awesome-runbooks
    component: awesome-runbooks
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $val := .Values.global.commonLabels }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      component: awesome-runbooks
  template:
    metadata:
      labels:
        app: awesome-runbooks
        component: awesome-runbooks
      {{- range $key, $val := .Values.global.commonLabels }}
        {{ $key }}: "{{ $val }}"
      {{- end }}
    spec:
      # Created by this chart.
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      containers:
      - name: awesome-runbooks
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        ports:
        {{ with index .Values.service.ports 0 }}
        - containerPort: {{ .port }}
        {{- end }}
        {{- if .Values.deployment.resources }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
        {{- end }}

  {{- if .Values.persistence.enabled }}
        volumeMounts:
        - name: credentials
          mountPath: {{ .Values.persistence.mountpath }}
      volumes:
        - name: credentials
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}

  {{- if .Values.deployment.tolerations }}
      tolerations:
      {{- toYaml .Values.deployment.tolerations | nindent 8 }}
  {{- end }}
  {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
  {{- end }}
  {{- if .Values.deployment.affinity }}
      affinity:
      {{- toYaml .Values.deployment.affinity | nindent 8 }}
  {{- end }}

  {{- end }}
{{- end }}
