name: Create New Action
description: File an Action Request
title: "[Action]: "
labels: ["action", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new Action!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: checkboxes
    id: healthcheck
    attributes:
      label: HealthCheck
      description: Check Actions can be used in the Healthcheck flow
      options:
        - label: Is this Action a Check Action?
  - type: textarea
    id: Actionname
    attributes:
      label: Action Name
      description: What is the Name for your Action?
      placeholder: List all Open GitHub Pull Requests
    validations:
      required: true
  - type: textarea
    id: Actioninputs
    attributes:
      label: Action Inputs
      description: What variables (and variable types) do you expect for this action
      placeholder: region instance_id
    validations:
      required: true
  - type: textarea
    id: Actionoutputs
    attributes:
      label: Action Outputs
      description: What do you want to see in the Action output (and type)
      placeholder: list of all IP addresses
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Do you have any additional information for this Action?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
