@startuml

class GlobalConfig {
    - enable_runbooks: bool
    - audit_period: int
}

class ChecksConfig {
    - arguments: dict
}

class Credential {
    - aws: dict
    - k8s: dict
    - gcp: dict
    - elasticsearch: dict
    - redis: dict
    - postgres: dict
    - mongodb: dict
    - kafka: dict
    - rest: dict
    - vault: dict
    - keycloak: dict
}

class NotificationConfig {
    - Slack: dict
    - Email: dict
}

class JobDetail {
    - name: str
    - notify: bool
    - enable: bool
    - checks: list
    - suites: list
    - connector_types: list
    - custom_scripts: list
}

class SchedulerConfig {
    - enable: bool
    - cadence: str
    - job_name: str
}

GlobalConfig o-- ChecksConfig
GlobalConfig o-- Credential
GlobalConfig o-- NotificationConfig
GlobalConfig o-- JobDetail
GlobalConfig o-- SchedulerConfig

@enduml