@startuml
abstract class DatabaseFactory {
    - init() : dataclass 
    - create_db()
    - drop_db()
    - create()
    - read() : cachedmethod
    - update()
    - delete()
}

class ZoDBInterface extends DatabaseFactory {
    - init()
    + create_db()
    + drop_db()
    + create()
    + read()
    + update()
    + delete()
}

class SQLInterface extends DatabaseFactory {
    - init()
    + create_db()
    + drop_db()
    + create()
    + read()
    + update()
    + delete()
}

class DBInterface {
    - db 
    - init(self, db_name='zodb') : ZoDBInterface or SQLInterface
}

DBInterface --> SQLInterface
DBInterface --> ZoDBInterface


@enduml