@startuml
package "TestFunctional" {
    class "TestFunctional" {
        + test_functional()
    }

    package "Mocks" {
        class "ArgumentParserMock" {
            + ShowRunOptions()
            + ShowListOptions()
            + ShowShowOptions()
            + ShowDebugOptions()
        }

        class "ConfigParserMock" {
            + ReadYAMLFile()
            + ParseGlobalConfig()
            + ParseJobsConfig()
            + ParseScheduleConfig()
            + ParseCredentialConfig()
            + ParseNotificationConfig()
        }


        class "NotificationMock" {
            + SlackNotify()
            + EmailNotify()
        }

        class "DatabaseInterfaceMock" {
            + create()
            + update()
            + delete()
            + read()
        }

        class "RunnerMocks" {
            + RunChecksByName()
            + RunChecks()
            + RunScript()
            + RunRunbook()
        }
    }

    "TestFunctional" --> "Mocks"

    note right of "Mocks" : Each class represents\na specific mock\nwith its respective\nmethods.

    "TestFunctional" --> "ArgumentParserMock" : Uses
    "TestFunctional" --> "ConfigParserMock" : Uses
    "TestFunctional" --> "InstanceMock" : Uses
    "TestFunctional" --> "NotificationMock" : Uses
    "TestFunctional" --> "DatabaseInterfaceMock" : Uses
    "TestFunctional" --> "RunnerMocks" : Uses
}
@enduml
