global:
  # Create RBAC resources
  rbac: true
  commonLabels: {}
    # app.kubernetes.io/name: [your app name]


# COMMENT (FIXME)
image: unskript/awesome-runbooks:latest
# Enterprise Gateway image pull policy.
imagePullPolicy: Always
# K8s Enterprise Gateway Service
service:
  type: "NodePort"
  externalIPs:
    # Master public IP on which to expose EG.
    k8sMasterPublicIP: ''
  ports:
    # The primary port on which Enterprise Gateway is servicing requests.
    - name: "http"
      port: 8888
      targetPort: 8888


deployment:
  enabled: true
  serviceAccountName: 'awesome-runbooks-sa'
  terminationGracePeriodSeconds: 30
  annotations: {}
  resources: {}
  replicas: 1
  tolerations: []
  affinity: {}
  nodeSelector: {}


# Log output level.
logLevel: DEBUG


# FIX ME. Replace MongoDB style of persistence 
credentialPvc:
  enabled: false
  name:
