global:
  # Create RBAC resources
  rbac: true
  commonLabels: {}
    # app.kubernetes.io/name: [your app name]


# @param image is the location of the docker image you want to pull from
#        If you have a custom docker build, you may want to change the location
#        below to the custom docker build.
image: unskript/awesome-runbooks:latest
imagePullPolicy: Always
service:
  type: "NodePort"
  externalIPs:
    k8sMasterPublicIP: ''
  ports:
    - name: "http"
      port: 8888
      targetPort: 8888


deployment:
  enabled: true
  serviceAccountName: 'awesome-runbooks-sa'
  terminationGracePeriodSeconds: 30
  annotations: {}
  resources: {}
  replicas: 1
  tolerations: []
  affinity: {}
  nodeSelector: {}


# Log output level.
logLevel: DEBUG



## Enable persistence using Persistent Volume Claims
## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  mountpath: "/unskript"
  name: